# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.10.7 on 2017-06-08 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dicts', '0003_professionalarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(max_length=255, verbose_name='Компания')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Компания')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Компания')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='Компания')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('phone_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('phone_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('phone_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт')),
                ('website_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт')),
                ('website_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт')),
                ('website_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('address_ru', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('address_fr', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('map_y', models.FloatField(blank=True, null=True, verbose_name='Координата Y (широта)')),
                ('map_x', models.FloatField(blank=True, null=True, verbose_name='Координата X (долгота)')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='dicts.City', verbose_name='Город')),
                ('professional_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='dicts.ProfessionalArea', verbose_name='Направление деятельности')),
            ],
            options={
                'verbose_name': 'Дилер',
                'verbose_name_plural': 'Дилеры',
            },
        ),
    ]
