# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-28 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170528_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsection',
            options={'verbose_name': 'Секция новости', 'verbose_name_plural': 'Секция новости'},
        ),
        migrations.AddField(
            model_name='project',
            name='bg',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projects', verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, max_length=255, null=True, upload_to='articles/%Y/%m/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Gallery', verbose_name='Галерея фотографий'),
        ),
    ]
