# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-28 21:40
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0003_auto_20170528_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, max_length=255, null=True, upload_to='articles/%Y/%m/', verbose_name='Изображение'),
        ),
    ]
