# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-06 15:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import snippets.utils.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dicts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_fr', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Разрешены только латинские символы, цифры, символ подчеркивания и дефис (минус)', max_length=150, unique=True, verbose_name='Алиас')),
                ('publish_date', models.DateTimeField(db_index=True, default=snippets.utils.datetime.utcnow, help_text='Можно задать на будущее', verbose_name='Дата публикации')),
                ('image', image_cropping.fields.ImageCropField(blank=True, max_length=255, null=True, upload_to='news', verbose_name='Изображение')),
                ('thumb_list', image_cropping.fields.ImageRatioField('image', '200x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Эскиз в списке')),
                ('excerpt', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Анонс')),
                ('excerpt_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Анонс')),
                ('excerpt_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Анонс')),
                ('excerpt_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Анонс')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Выводится выше всех секций', verbose_name='Контент')),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Выводится выше всех секций', null=True, verbose_name='Контент')),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Выводится выше всех секций', null=True, verbose_name='Контент')),
                ('body_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Выводится выше всех секций', null=True, verbose_name='Контент')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_finish', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('participants_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество участников')),
                ('body_about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='О курсе')),
                ('body_about_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='О курсе')),
                ('body_about_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='О курсе')),
                ('body_about_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='О курсе')),
                ('body_detail', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Подробная информация')),
                ('body_detail_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Подробная информация')),
                ('body_detail_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Подробная информация')),
                ('body_detail_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Подробная информация')),
                ('body_schedule', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Текст над таблицей', null=True, verbose_name='Расписание')),
                ('body_schedule_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Текст над таблицей', null=True, verbose_name='Расписание')),
                ('body_schedule_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Текст над таблицей', null=True, verbose_name='Расписание')),
                ('body_schedule_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Текст над таблицей', null=True, verbose_name='Расписание')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='dicts.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('schedule_date', models.DateField(blank=True, help_text='Не указывайте, если в течение одного дня', null=True, verbose_name='Дата')),
                ('schedule_time', models.TimeField(verbose_name='Время')),
                ('title', models.CharField(max_length=255, verbose_name='Мероприятие')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Мероприятие')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Мероприятие')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='Мероприятие')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='training.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Строка расписания курса',
                'verbose_name_plural': 'Расписание курса',
            },
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('teacher_role', models.CharField(blank=True, help_text='Например, "лектор"', max_length=100, null=True, verbose_name='Роль преподавателя')),
                ('teacher_role_ru', models.CharField(blank=True, help_text='Например, "лектор"', max_length=100, null=True, verbose_name='Роль преподавателя')),
                ('teacher_role_en', models.CharField(blank=True, help_text='Например, "лектор"', max_length=100, null=True, verbose_name='Роль преподавателя')),
                ('teacher_role_fr', models.CharField(blank=True, help_text='Например, "лектор"', max_length=100, null=True, verbose_name='Роль преподавателя')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Преподаватель курса',
                'verbose_name_plural': 'Преподаватели курса',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Имя')),
                ('title_ru', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Имя')),
                ('title_en', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Имя')),
                ('title_fr', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Имя')),
                ('image', image_cropping.fields.ImageCropField(blank=True, max_length=254, null=True, upload_to='teachers', verbose_name='Аватар')),
                ('image_thumb', image_cropping.fields.ImageRatioField('image', '180x180', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Эскиз')),
                ('courses', models.ManyToManyField(blank=True, through='training.CourseTeacher', to='training.Course', verbose_name='Курсы')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Teacher', verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(through='training.CourseTeacher', to='training.Teacher', verbose_name='Преподаватели'),
        ),
    ]
