# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-29 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20170529_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='course',
            name='excerpt_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='excerpt_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='excerpt_ru',
        ),
    ]
