# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-29 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20170529_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseschedule',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='schedule_time',
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='period',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время от/до'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='period_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Время от/до'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='period_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Время от/до'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='period_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Время от/до'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='title_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Мероприятие'),
        ),
    ]
