# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_auto_20170620_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bg',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='courses', verbose_name='Фон описания о курсе'),
        ),
    ]
