# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_course_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail_bg',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='courses', verbose_name='Фон подробного описания о курсе'),
        ),
    ]
