# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 20:19
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_course_detail_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image_thumb',
            field=image_cropping.fields.ImageRatioField('image', '200x200', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Эскиз'),
        ),
    ]
