# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-12 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('icon', models.CharField(blank=True, choices=[('antibiotic', 'Антибиотик'), ('bacteria', 'Бактерия'), ('braces', 'Брекеты'), ('cardiogram', 'Кардиограмма'), ('dental-drill', 'Бормашина'), ('electric-toothbrush', 'Электрическая зубная щетка'), ('implants', 'Имплант'), ('medical-records', 'Врачебная запись'), ('mirror', 'Зеркало'), ('molar', 'Коренной, бормашина'), ('molar-1', 'Коренной, крупно'), ('molar-2', 'Корренной, мелко, с десной'), ('molar-crown', 'Коронка'), ('periodontal-scaler', 'Скалер'), ('premolar', 'Малый коренной'), ('records', 'Диагностика 1'), ('records-1', 'Диагностика 2'), ('search', 'Поиск, лупа'), ('teeth', 'Зуб, пломба'), ('tooth', 'Зуб, блеск'), ('tooth-1', 'Зуб в разрезе'), ('tweezers', 'Пинцет'), ('virus', 'Вирус'), ('x-ray', 'Рентген')], max_length=50, null=True, verbose_name='Иконка')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name_plural': 'Преимущества на главной странице',
                'verbose_name': 'Преимущество',
            },
        ),
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('image', models.ImageField(max_length=255, upload_to='homepage_slides', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('subtitle_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('subtitle_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка кнопки')),
                ('url_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка кнопки')),
                ('url_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка кнопки')),
                ('url_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка кнопки')),
                ('button_caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки')),
                ('button_caption_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки')),
                ('button_caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки')),
                ('button_caption_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name_plural': 'Слайды на главной',
                'verbose_name': 'Слайд на главной',
            },
        ),
    ]
