# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-14 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homeadvantage_homeslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslide',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='homepage_slides', verbose_name='Изображение'),
        ),
    ]
