# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-24 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170512_0933'),
        ('core', '0003_auto_20170514_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('subtitle_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('subtitle_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка кнопки')),
                ('link_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка кнопки')),
                ('link_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка кнопки')),
                ('link_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка кнопки')),
                ('button_caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки')),
                ('button_caption_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки')),
                ('button_caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки')),
                ('button_caption_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки')),
                ('banner_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок баннера')),
                ('banner_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок баннера')),
                ('banner_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок баннера')),
                ('banner_title_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок баннера')),
                ('banner_subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок баннера')),
                ('banner_subtitle_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок баннера')),
                ('banner_subtitle_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок баннера')),
                ('banner_subtitle_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок баннера')),
            ],
            options={
                'verbose_name_plural': 'Каталоги на главной',
                'verbose_name': 'Каталог на главной',
            },
        ),
        migrations.CreateModel(
            name='HomeCatalogManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='core.HomeCatalog', verbose_name='Каталог')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_catalogs', to='catalog.Manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name_plural': 'Производители каталога главной',
                'verbose_name': 'Производитель каталога на главной',
            },
        ),
        migrations.CreateModel(
            name='HomeCatalogProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.HomeCatalog', verbose_name='Каталог')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_catalogs', to='catalog.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name_plural': 'Продукты каталога главной',
                'verbose_name': 'Продукт каталога на главной',
            },
        ),
        migrations.AlterField(
            model_name='homeadvantage',
            name='icon',
            field=models.CharField(blank=True, choices=[('antibiotic', 'Антибиотик'), ('bacteria', 'Бактерия'), ('braces', 'Брекеты'), ('cardiogram', 'Кардиограмма'), ('dental-drill', 'Бормашина'), ('dental-pin', 'Зубы и штифт'), ('electric-toothbrush', 'Электрическая зубная щетка'), ('implants', 'Имплант'), ('medical-records', 'Врачебная запись'), ('mirror', 'Зеркало'), ('molar', 'Коренной, бормашина'), ('molar-1', 'Коренной, крупно'), ('molar-2', 'Корренной, мелко, с десной'), ('molar-crown', 'Коронка'), ('periodontal-scaler', 'Скалер'), ('premolar', 'Малый коренной'), ('records', 'Диагностика 1'), ('records-1', 'Диагностика 2'), ('search', 'Поиск, лупа'), ('teeth', 'Зуб, пломба'), ('tooth', 'Зуб, блеск'), ('tooth-1', 'Зуб в разрезе'), ('tweezers', 'Пинцет'), ('virus', 'Вирус'), ('x-ray', 'Рентген')], max_length=50, null=True, verbose_name='Иконка'),
        ),
    ]
