# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170525_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslide',
            name='bg',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='homepage_slides', verbose_name='Фон'),
        ),
        migrations.AddField(
            model_name='homeslide',
            name='image_on_left',
            field=models.BooleanField(default=False, verbose_name='Изображение слева'),
        ),
        migrations.AlterField(
            model_name='homeadvantage',
            name='icon',
            field=models.CharField(blank=True, choices=[('antibiotic', 'Антибиотик'), ('bacteria', 'Бактерия'), ('braces', 'Брекеты'), ('dental-drill', 'Бормашина'), ('virus', 'Вирус'), ('medical-records', 'Врачебная запись'), ('records', 'Диагностика 1'), ('records-1', 'Диагностика 2'), ('mirror', 'Зеркало'), ('teeth', 'Зуб, пломба'), ('tooth', 'Зуб, блеск'), ('tooth-1', 'Зуб в разрезе'), ('dental-pin', 'Зубы и штифт'), ('implants', 'Имплант'), ('cardiogram', 'Кардиограмма'), ('molar-crown', 'Коронка'), ('molar', 'Коренной, бормашина'), ('molar-1', 'Коренной, крупно'), ('molar-2', 'Корренной, мелко, с десной'), ('premolar', 'Малый коренной'), ('tweezers', 'Пинцет'), ('search', 'Поиск, лупа'), ('x-ray', 'Рентген'), ('periodontal-scaler', 'Скалер'), ('electric-toothbrush', 'Электрическая зубная щетка')], max_length=50, null=True, verbose_name='Иконка'),
        ),
    ]
