# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-06 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('catalog', '0001_initial'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('fr', 'Français')], default='ru', max_length=6, verbose_name='Язык')),
                ('read_status', models.SmallIntegerField(choices=[(-1, 'Новый'), (1, 'Прочитан')], default=-1, verbose_name='Статус прочтения')),
                ('name', models.CharField(max_length=255, verbose_name='Имя и фамилия')),
                ('telephone_email', models.CharField(max_length=254, verbose_name='Телефон или email')),
                ('comment', models.TextField(max_length=32768, verbose_name='Комментарий')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=0, help_text='При отключении публикации будут скрываться и ответы на комментарий', verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, help_text='для внутренного использования, не выводится на сайте!', null=True, verbose_name='Комментарий')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Тип объекта')),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forms.Comment', verbose_name='Ответы')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='EducationFormRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('fr', 'Français')], default='ru', max_length=6, verbose_name='Язык')),
                ('read_status', models.SmallIntegerField(choices=[(-1, 'Новый'), (1, 'Прочитан')], default=-1, verbose_name='Статус прочтения')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('telephone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_requests', to='education.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Запрос на обучение',
                'verbose_name_plural': 'Обучение',
            },
        ),
        migrations.CreateModel(
            name='FeedbackFormRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('fr', 'Français')], default='ru', max_length=6, verbose_name='Язык')),
                ('read_status', models.SmallIntegerField(choices=[(-1, 'Новый'), (1, 'Прочитан')], default=-1, verbose_name='Статус прочтения')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('telephone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, max_length=32768, null=True, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Запрос обратной связи',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='PartnershipFormRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('fr', 'Français')], default='ru', max_length=6, verbose_name='Язык')),
                ('read_status', models.SmallIntegerField(choices=[(-1, 'Новый'), (1, 'Прочитан')], default=-1, verbose_name='Статус прочтения')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('telephone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, max_length=32768, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Запрос сотрудничества',
                'verbose_name_plural': 'Сотрудничество',
            },
        ),
        migrations.CreateModel(
            name='ProductProposalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('fr', 'Français')], default='ru', max_length=6, verbose_name='Язык')),
                ('read_status', models.SmallIntegerField(choices=[(-1, 'Новый'), (1, 'Прочитан')], default=-1, verbose_name='Статус прочтения')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('telephone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('comment', models.TextField(blank=True, max_length=32768, null=True, verbose_name='Комментарий')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_proposals', to='catalog.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Запрос КП по продукту',
                'verbose_name_plural': 'Запросы КП по продуктам',
            },
        ),
        migrations.CreateModel(
            name='ProductQuestionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('fr', 'Français')], default='ru', max_length=6, verbose_name='Язык')),
                ('read_status', models.SmallIntegerField(choices=[(-1, 'Новый'), (1, 'Прочитан')], default=-1, verbose_name='Статус прочтения')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('telephone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('comment', models.TextField(blank=True, max_length=32768, null=True, verbose_name='Комментарий')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_requests', to='catalog.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Вопрос по продукту',
                'verbose_name_plural': 'Вопросы по продуктам',
            },
        ),
        migrations.CreateModel(
            name='PurchaseFormRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('fr', 'Français')], default='ru', max_length=6, verbose_name='Язык')),
                ('read_status', models.SmallIntegerField(choices=[(-1, 'Новый'), (1, 'Прочитан')], default=-1, verbose_name='Статус прочтения')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('telephone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, max_length=32768, null=True, verbose_name='Комментарий')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='catalog.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Запрос закупки',
                'verbose_name_plural': 'Закупка',
            },
        ),
        migrations.CreateModel(
            name='ServiceFormRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('fr', 'Français')], default='ru', max_length=6, verbose_name='Язык')),
                ('read_status', models.SmallIntegerField(choices=[(-1, 'Новый'), (1, 'Прочитан')], default=-1, verbose_name='Статус прочтения')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('telephone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('comment', models.TextField(blank=True, max_length=32768, null=True, verbose_name='Проблема')),
            ],
            options={
                'verbose_name': 'Запрос сервисного центра',
                'verbose_name_plural': 'Сервисный центр',
            },
        ),
        migrations.CreateModel(
            name='SupportFormRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('fr', 'Français')], default='ru', max_length=6, verbose_name='Язык')),
                ('read_status', models.SmallIntegerField(choices=[(-1, 'Новый'), (1, 'Прочитан')], default=-1, verbose_name='Статус прочтения')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('product_code', models.CharField(max_length=255, verbose_name='Полное название товара, серия')),
                ('comment', models.TextField(blank=True, max_length=32768, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Запрос тех.поддержки',
                'verbose_name_plural': 'Тех.поддержка',
            },
        ),
    ]
