# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-06 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploadifive', '0001_initial'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='uploadifive.Upload', verbose_name='Аватар'),
        ),
    ]
