# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.10.7 on 2017-06-07 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20170608_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproposalrequest',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='productquestionrequest',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='productquestionrequest',
            name='comment',
            field=models.TextField(max_length=32768, verbose_name='Комментарий'),
        ),
    ]
