# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.10.7 on 2017-06-08 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportsection_categories'),
        ('forms', '0007_feedbackformrequest_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportformrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_requests', to='support.SupportCategory', verbose_name='Категория сервисного цнтра'),
        ),
    ]
