# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.10.7 on 2017-05-31 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportsection',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='sections', to='support.SupportCategory', verbose_name='Категории'),
        ),
    ]
