# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-02 17:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('icon', models.CharField(blank=True, choices=[('antibiotic', 'Антибиотик'), ('bacteria', 'Бактерия'), ('braces', 'Брекеты'), ('cardiogram', 'Кардиограмма'), ('dental-drill', 'Бормашина'), ('electric-toothbrush', 'Электрическая зубная щетка'), ('implants', 'Имплант'), ('medical-records', 'Врачебная запись'), ('mirror', 'Зеркало'), ('molar', 'Коренной, бормашина'), ('molar-1', 'Коренной, крупно'), ('molar-2', 'Корренной, мелко, с десной'), ('molar-crown', 'Коронка'), ('periodontal-scaler', 'Скалер'), ('premolar', 'Малый коренной'), ('records', 'Диагностика 1'), ('records-1', 'Диагностика 2'), ('search', 'Поиск, лупа'), ('teeth', 'Зуб, пломба'), ('tooth', 'Зуб, блеск'), ('tooth-1', 'Зуб в разрезе'), ('tweezers', 'Пинцет'), ('virus', 'Вирус'), ('x-ray', 'Рентген')], max_length=50, null=True, verbose_name='Иконка')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества на странице "О компании"',
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы')),
                ('subtitle', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=4096, null=True, verbose_name='Подзаголовок')),
                ('subtitle_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=4096, null=True, verbose_name='Подзаголовок')),
                ('subtitle_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=4096, null=True, verbose_name='Подзаголовок')),
                ('quote_image', image_cropping.fields.ImageCropField(blank=True, max_length=255, null=True, upload_to='about', verbose_name='Фото в цитате')),
                ('quote_image_ru', image_cropping.fields.ImageCropField(blank=True, max_length=255, null=True, upload_to='about', verbose_name='Фото в цитате')),
                ('quote_image_en', image_cropping.fields.ImageCropField(blank=True, max_length=255, null=True, upload_to='about', verbose_name='Фото в цитате')),
                ('quote_thumb', image_cropping.fields.ImageRatioField('quote_image', '110x110', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Эскиз в цитате')),
                ('quote', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Цитата')),
                ('quote_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Цитата')),
                ('quote_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Цитата')),
                ('quoted_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цитируемый человек')),
                ('quoted_person_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цитируемый человек')),
                ('quoted_person_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цитируемый человек')),
                ('main_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Главный контент')),
                ('main_body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Главный контент')),
                ('main_body_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Главный контент')),
                ('guarantee_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок гарантий')),
                ('guarantee_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок гарантий')),
                ('guarantee_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок гарантий')),
                ('guarantee_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент гарантий')),
                ('guarantee_body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент гарантий')),
                ('guarantee_body_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент гарантий')),
                ('questions_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока "Есть вопросы?"')),
                ('questions_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока "Есть вопросы?"')),
                ('questions_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока "Есть вопросы?"')),
                ('questions_subtitle', models.TextField(blank=True, null=True, verbose_name='Подзаголовок блока "Есть вопросы?"')),
                ('questions_subtitle_ru', models.TextField(blank=True, null=True, verbose_name='Подзаголовок блока "Есть вопросы?"')),
                ('questions_subtitle_en', models.TextField(blank=True, null=True, verbose_name='Подзаголовок блока "Есть вопросы?"')),
            ],
            options={
                'verbose_name': 'Страница "О компании"',
            },
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы')),
                ('address', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Адрес в контактах')),
                ('address_ru', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Адрес в контактах')),
                ('address_en', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Адрес в контактах')),
                ('questions_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока "Есть вопросы?"')),
                ('questions_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока "Есть вопросы?"')),
                ('questions_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока "Есть вопросы?"')),
                ('questions_subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок блока "Есть вопросы?"')),
                ('questions_subtitle_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок блока "Есть вопросы?"')),
                ('questions_subtitle_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок блока "Есть вопросы?"')),
                ('map_y', models.FloatField(verbose_name='Координата Y (широта)')),
                ('map_y_ru', models.FloatField(null=True, verbose_name='Координата Y (широта)')),
                ('map_y_en', models.FloatField(null=True, verbose_name='Координата Y (широта)')),
                ('map_x', models.FloatField(verbose_name='Координата X (долгота)')),
                ('map_x_ru', models.FloatField(null=True, verbose_name='Координата X (долгота)')),
                ('map_x_en', models.FloatField(null=True, verbose_name='Координата X (долгота)')),
                ('map_zoom', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=16, verbose_name='Масштаб карты')),
                ('map_zoom_ru', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=16, null=True, verbose_name='Масштаб карты')),
                ('map_zoom_en', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=16, null=True, verbose_name='Масштаб карты')),
            ],
            options={
                'verbose_name': 'Страница "Контакты"',
            },
        ),
        migrations.CreateModel(
            name='HomeAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('icon', models.CharField(blank=True, choices=[('antibiotic', 'Антибиотик'), ('bacteria', 'Бактерия'), ('braces', 'Брекеты'), ('cardiogram', 'Кардиограмма'), ('dental-drill', 'Бормашина'), ('electric-toothbrush', 'Электрическая зубная щетка'), ('implants', 'Имплант'), ('medical-records', 'Врачебная запись'), ('mirror', 'Зеркало'), ('molar', 'Коренной, бормашина'), ('molar-1', 'Коренной, крупно'), ('molar-2', 'Корренной, мелко, с десной'), ('molar-crown', 'Коронка'), ('periodontal-scaler', 'Скалер'), ('premolar', 'Малый коренной'), ('records', 'Диагностика 1'), ('records-1', 'Диагностика 2'), ('search', 'Поиск, лупа'), ('teeth', 'Зуб, пломба'), ('tooth', 'Зуб, блеск'), ('tooth-1', 'Зуб в разрезе'), ('tweezers', 'Пинцет'), ('virus', 'Вирус'), ('x-ray', 'Рентген')], max_length=50, null=True, verbose_name='Иконка')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества на странице "О компании"',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы')),
                ('subtitle', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=4096, null=True, verbose_name='Подзаголовок')),
                ('subtitle_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=4096, null=True, verbose_name='Подзаголовок')),
                ('subtitle_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=4096, null=True, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
        ),
        migrations.AddField(
            model_name='homeadvantage',
            name='home_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='pages.HomePage', verbose_name='Главная страница'),
        ),
        migrations.AddField(
            model_name='aboutadvantage',
            name='about_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='pages.AboutPage', verbose_name='Страница "О компании"'),
        ),
    ]
