# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-12 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homeslide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_ru',
        ),
    ]
