# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-12 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20170512_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeadvantage',
            name='home_page',
        ),
        migrations.RemoveField(
            model_name='homeslide',
            name='home_page',
        ),
        migrations.DeleteModel(
            name='HomeAdvantage',
        ),
        migrations.DeleteModel(
            name='HomeSlide',
        ),
    ]
