# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-14 11:59
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20170514_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='quote_thumb',
        ),
        migrations.AddField(
            model_name='aboutadvantage',
            name='subtitle_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='aboutadvantage',
            name='subtitle_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='aboutadvantage',
            name='subtitle_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='aboutadvantage',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutadvantage',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutadvantage',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='quote_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='about', verbose_name='Фото в цитате'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='quote_image_en',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='about', verbose_name='Фото в цитате'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='quote_image_fr',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='about', verbose_name='Фото в цитате'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='quote_image_ru',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='about', verbose_name='Фото в цитате'),
        ),
    ]
