# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-14 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20170514_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='guarantee_body',
            field=models.TextField(blank=True, null=True, verbose_name='Контент гарантий'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='guarantee_body_en',
            field=models.TextField(blank=True, null=True, verbose_name='Контент гарантий'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='guarantee_body_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Контент гарантий'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='guarantee_body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Контент гарантий'),
        ),
    ]
