# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-24 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20170514_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutadvantage',
            name='icon',
            field=models.CharField(blank=True, choices=[('antibiotic', 'Антибиотик'), ('bacteria', 'Бактерия'), ('braces', 'Брекеты'), ('cardiogram', 'Кардиограмма'), ('dental-drill', 'Бормашина'), ('dental-pin', 'Зубы и штифт'), ('electric-toothbrush', 'Электрическая зубная щетка'), ('implants', 'Имплант'), ('medical-records', 'Врачебная запись'), ('mirror', 'Зеркало'), ('molar', 'Коренной, бормашина'), ('molar-1', 'Коренной, крупно'), ('molar-2', 'Корренной, мелко, с десной'), ('molar-crown', 'Коронка'), ('periodontal-scaler', 'Скалер'), ('premolar', 'Малый коренной'), ('records', 'Диагностика 1'), ('records-1', 'Диагностика 2'), ('search', 'Поиск, лупа'), ('teeth', 'Зуб, пломба'), ('tooth', 'Зуб, блеск'), ('tooth-1', 'Зуб в разрезе'), ('tweezers', 'Пинцет'), ('virus', 'Вирус'), ('x-ray', 'Рентген')], max_length=50, null=True, verbose_name='Иконка'),
        ),
    ]
