# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-29 22:16
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20170527_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCenterPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы')),
                ('subtitle', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=4096, null=True, verbose_name='Подзаголовок страницы')),
                ('subtitle_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=4096, null=True, verbose_name='Подзаголовок страницы')),
                ('subtitle_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=4096, null=True, verbose_name='Подзаголовок страницы')),
                ('subtitle_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=4096, null=True, verbose_name='Подзаголовок страницы')),
                ('bg', models.ImageField(blank=True, max_length=255, null=True, upload_to='pages', verbose_name='Фон')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент')),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('body_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('request_order_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока "Порядок обращения"')),
                ('request_order_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока "Порядок обращения"')),
                ('request_order_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока "Порядок обращения"')),
                ('request_order_title_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока "Порядок обращения"')),
                ('questions_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока "Есть вопросы?"')),
                ('questions_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока "Есть вопросы?"')),
                ('questions_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока "Есть вопросы?"')),
                ('questions_title_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока "Есть вопросы?"')),
                ('questions_subtitle', models.TextField(blank=True, null=True, verbose_name='Подзаголовок блока "Есть вопросы?"')),
                ('questions_subtitle_ru', models.TextField(blank=True, null=True, verbose_name='Подзаголовок блока "Есть вопросы?"')),
                ('questions_subtitle_en', models.TextField(blank=True, null=True, verbose_name='Подзаголовок блока "Есть вопросы?"')),
                ('questions_subtitle_fr', models.TextField(blank=True, null=True, verbose_name='Подзаголовок блока "Есть вопросы?"')),
                ('questions_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='pages', verbose_name='Изображения блока "Есть вопросы?"')),
            ],
            options={
                'verbose_name': 'Страница "Сервисный центр"',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('icon', models.CharField(blank=True, choices=[('antibiotic', 'Антибиотик'), ('bacteria', 'Бактерия'), ('braces', 'Брекеты'), ('dental-drill', 'Бормашина'), ('virus', 'Вирус'), ('medical-records', 'Врачебная запись'), ('records', 'Диагностика 1'), ('records-1', 'Диагностика 2'), ('mirror', 'Зеркало'), ('teeth', 'Зуб, пломба'), ('tooth', 'Зуб, блеск'), ('tooth-1', 'Зуб в разрезе'), ('dental-pin', 'Зубы и штифт'), ('implants', 'Имплант'), ('cardiogram', 'Кардиограмма'), ('molar-crown', 'Коронка'), ('molar', 'Коренной, бормашина'), ('molar-1', 'Коренной, крупно'), ('molar-2', 'Корренной, мелко, с десной'), ('premolar', 'Малый коренной'), ('tweezers', 'Пинцет'), ('search', 'Поиск, лупа'), ('x-ray', 'Рентген'), ('periodontal-scaler', 'Скалер'), ('electric-toothbrush', 'Электрическая зубная щетка')], max_length=50, null=True, verbose_name='Иконка')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('service_center_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_order', to='pages.ServiceCenterPage', verbose_name='Страница "Сервисный центр"')),
            ],
            options={
                'verbose_name_plural': 'Порядок обращения в сервисный центр',
                'verbose_name': 'Порядок обращения в сервисный центр',
            },
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='bg',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pages', verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='subtitle',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=4096, null=True, verbose_name='Подзаголовок страницы'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='subtitle_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=4096, null=True, verbose_name='Подзаголовок страницы'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='subtitle_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=4096, null=True, verbose_name='Подзаголовок страницы'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='subtitle_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=4096, null=True, verbose_name='Подзаголовок страницы'),
        ),
    ]
