# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.10.7 on 2017-05-31 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20170531_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecenterpage',
            name='questions_image',
        ),
        migrations.AddField(
            model_name='servicecenterpage',
            name='questions_image_left',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pages', verbose_name='Изображения блока "Есть вопросы?" (слева)'),
        ),
        migrations.AddField(
            model_name='servicecenterpage',
            name='questions_image_right',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pages', verbose_name='Изображения блока "Есть вопросы?" (справа)'),
        ),
    ]
