# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-06 15:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import image_cropping.fields
import mptt.fields
import snippets.utils.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='Заголовок')),
                ('title_fr', models.CharField(max_length=255, null=True, unique=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Название')),
                ('title_fr', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Латинские буквы и цифры', max_length=150, unique=True, verbose_name='Алиас')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='manufacturers', verbose_name='Лого')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Наименование')),
                ('title_ru', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Наименование')),
                ('title_en', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Наименование')),
                ('title_fr', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(help_text='Латинские буквы и цифры', max_length=150, unique=True, verbose_name='Алиас')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Артикул')),
                ('image', image_cropping.fields.ImageCropField(blank=True, max_length=255, null=True, upload_to='products', verbose_name='Главное изображение')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Основной контент')),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Основной контент')),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Основной контент')),
                ('body_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Основной контент')),
                ('features_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент над характеристиками')),
                ('features_body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент над характеристиками')),
                ('features_body_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент над характеристиками')),
                ('features_body_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент над характеристиками')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Наименование')),
                ('title_ru', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Наименование')),
                ('title_en', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Наименование')),
                ('title_fr', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(help_text='Латинские буквы и цифры', max_length=150, unique=True, verbose_name='Алиас')),
                ('image', image_cropping.fields.ImageCropField(blank=True, max_length=255, null=True, upload_to='products', verbose_name='Изображение')),
                ('image_position', models.CharField(choices=[('left', 'Слева'), ('center', 'Посередине'), ('right', 'Снизу справа')], default='center', max_length=50, verbose_name='Расположение изображения')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент')),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('body_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Уровень')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.ProductCategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория продуктов',
                'verbose_name_plural': 'Категории продуктов',
            },
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('document', models.FileField(max_length=255, upload_to='products/docs', verbose_name='Документ')),
                ('document_ru', models.FileField(max_length=255, null=True, upload_to='products/docs', verbose_name='Документ')),
                ('document_en', models.FileField(max_length=255, null=True, upload_to='products/docs', verbose_name='Документ')),
                ('document_fr', models.FileField(max_length=255, null=True, upload_to='products/docs', verbose_name='Документ')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('publish_date', models.DateTimeField(db_index=True, default=snippets.utils.datetime.utcnow, verbose_name='Дата публикации')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Документ продукта',
                'verbose_name_plural': 'Документы продукта',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('value_ru', models.CharField(max_length=255, null=True, verbose_name='Значение')),
                ('value_en', models.CharField(max_length=255, null=True, verbose_name='Значение')),
                ('value_fr', models.CharField(max_length=255, null=True, verbose_name='Значение')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='catalog.Feature', verbose_name='Характеристика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='catalog.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товара',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('image', image_cropping.fields.ImageCropField(max_length=255, upload_to='products/images', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, help_text='Альтернативный текст вместо изображения', max_length=255, null=True, verbose_name='Подпись (alt)')),
                ('alt_ru', models.CharField(blank=True, help_text='Альтернативный текст вместо изображения', max_length=255, null=True, verbose_name='Подпись (alt)')),
                ('alt_en', models.CharField(blank=True, help_text='Альтернативный текст вместо изображения', max_length=255, null=True, verbose_name='Подпись (alt)')),
                ('alt_fr', models.CharField(blank=True, help_text='Альтернативный текст вместо изображения', max_length=255, null=True, verbose_name='Подпись (alt)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продукта',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.ProductCategory', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.Manufacturer', verbose_name='Производитель'),
        ),
    ]
