# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-03 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
    ]
