# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-26 18:11
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170525_1230'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productcategory',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='seo_block_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент SEO-блока'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='seo_block_body_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент SEO-блока'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='seo_block_body_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент SEO-блока'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='seo_block_body_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент SEO-блока'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='seo_block_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок SEO-блока'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='seo_block_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок SEO-блока'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='seo_block_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок SEO-блока'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='seo_block_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок SEO-блока'),
        ),
    ]
