# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-27 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170526_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='seo_block_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/seo', verbose_name='Изображение в SEO-блоке'),
        ),
    ]
