# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-27 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productcategory_seo_block_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatureMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('hint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсказка')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features_main', to='catalog.Feature', verbose_name='Характеристика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_main', to='catalog.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name_plural': 'Главные характеристики товара',
                'verbose_name': 'Главная характеристика товара',
            },
        ),
        migrations.AddField(
            model_name='productfeature',
            name='hint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсказка'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='hint_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсказка'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='hint_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсказка'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='hint_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсказка'),
        ),
    ]
