# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-27 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20170527_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumb_siblings',
            field=image_cropping.fields.ImageRatioField('image', '170x170', adapt_rotation=False, allow_fullsize=True, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Эскиз в навигации'),
        ),
        migrations.AddField(
            model_name='productfeaturemain',
            name='hint_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсказка'),
        ),
        migrations.AddField(
            model_name='productfeaturemain',
            name='hint_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсказка'),
        ),
        migrations.AddField(
            model_name='productfeaturemain',
            name='hint_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсказка'),
        ),
    ]
