# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-27 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20170527_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, help_text='Применяется в наборах', null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.TextField(blank=True, help_text='Применяется в наборах', null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_fr',
            field=models.TextField(blank=True, help_text='Применяется в наборах', null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ru',
            field=models.TextField(blank=True, help_text='Применяется в наборах', null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumb_images',
            field=image_cropping.fields.ImageRatioField('image', '800x600', adapt_rotation=False, allow_fullsize=True, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка полей'),
        ),
    ]
