# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.10.7 on 2017-07-27 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20170619_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_set',
        ),
        migrations.AddField(
            model_name='product',
            name='is_show_in_list',
            field=models.BooleanField(default=True, verbose_name='Показывать в списке'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(related_name='_product_related_products_+', to='catalog.Product', verbose_name='Связанные товары'),
        ),
    ]
