# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-02 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Заголовок')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('url_ru', models.CharField(max_length=255, null=True, verbose_name='URL')),
                ('url_en', models.CharField(max_length=255, null=True, verbose_name='URL')),
                ('class_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='CSS-класс для ссылки (a тэг)')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
