# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.10.7 on 2017-06-08 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0003_professionalarea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialNetwork',
        ),
    ]
