# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11 on 2017-05-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='comment',
        ),
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
